/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Page */
        get: operations["login_page_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Openapi Schema */
        get: operations["openapi_schema_api_openapi_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ops */
        post: operations["post_ops_api_ops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/block-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block Refs
         * @description On-demand ((uid)) resolution for refs pasted after the page payload
         *     loaded (pkm-y6af). `uids` is comma-separated; unknown uids are omitted
         *     (the client renders them unresolved, same as the payload path).
         */
        get: operations["get_block_refs_api_block_refs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/page/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_page__title__get"];
        put?: never;
        post?: never;
        /**
         * Delete Page
         * @description Deletes the page, its blocks, and any sidebar entry for it. Inbound
         *     [[links]] from other pages' block text are left as-is -- only the refs
         *     rows pointing at this page disappear (via target_page_id CASCADE).
         *
         *     Blocks are deleted explicitly (not left to the pages FK cascade) so the
         *     blocks_fts_ad trigger fires for every row -- a direct DELETE guarantees
         *     that; relying on cascade-triggered deletes to fire triggers is not safe.
         */
        delete: operations["delete_page_api_page__title__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Page
         * @description Idempotent: creating an existing page returns its row, not an error.
         */
        post: operations["create_page_api_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/unlinked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unlinked */
        get: operations["get_unlinked_api_unlinked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Journal */
        get: operations["get_journal_api_journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Query */
        get: operations["run_query_api_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Titles
         * @description Page-title completion for the editor's [[ / # popup.
         */
        get: operations["titles_api_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sidebar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sidebar */
        get: operations["get_sidebar_api_sidebar_get"];
        /** Reorder Sidebar Entries */
        put: operations["reorder_sidebar_entries_api_sidebar_put"];
        /** Add Sidebar Entry */
        post: operations["add_sidebar_entry_api_sidebar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sidebar/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Sidebar Entry */
        delete: operations["delete_sidebar_entry_api_sidebar__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Changes */
        get: operations["sync_changes_api_sync_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Snapshot */
        get: operations["sync_snapshot_api_sync_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{sha256}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_assets__sha256___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddSidebarEntryRequest */
        AddSidebarEntryRequest: {
            /** Title */
            title: string;
        };
        /** AssetUploadResponse */
        AssetUploadResponse: {
            /** Sha256 */
            sha256: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /** Url */
            url: string;
        };
        /** BacklinkGroup */
        BacklinkGroup: {
            /** Page Id */
            page_id: number;
            /** Page Title */
            page_title: string;
            /** Items */
            items: components["schemas"]["BacklinkItem"][];
        };
        /** BacklinkItem */
        BacklinkItem: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
            /** Breadcrumbs */
            breadcrumbs: string[];
        };
        /** Backlinks */
        Backlinks: {
            /** Groups */
            groups: components["schemas"]["BacklinkGroup"][];
            /** Total Pages */
            total_pages: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** BlockGroup */
        BlockGroup: {
            /** Page Id */
            page_id: number;
            /** Page Title */
            page_title: string;
            /** Items */
            items: components["schemas"]["GroupItem"][];
        };
        /** BlockNode */
        BlockNode: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
            /** Heading */
            heading: number | null;
            /** Collapsed */
            collapsed: boolean;
            /** Order Idx */
            order_idx: number;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
            /** Children */
            children: components["schemas"]["BlockNode"][];
        };
        /** BlockRefText */
        BlockRefText: {
            /** Text */
            text: string;
            /** Page Title */
            page_title: string;
        };
        /**
         * BlockRefsPayload
         * @description GET /api/block-refs: on-demand ((uid)) resolution.
         */
        BlockRefsPayload: {
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
        };
        /** Body_upload_asset_api_assets_post */
        Body_upload_asset_api_assets_post: {
            /** File */
            file: string;
        };
        /** ChangesPayload */
        ChangesPayload: {
            /**
             * Reset
             * @default false
             */
            reset: boolean;
            /** Next Since */
            next_since: number;
            /** Latest Seq */
            latest_seq: number;
            /** Pages */
            pages: components["schemas"]["SyncPage"][];
            /** Blocks */
            blocks: components["schemas"]["SyncBlock"][];
            /** Sidebar */
            sidebar: components["schemas"]["SyncSidebarEntry"][];
            /** Tombstones */
            tombstones: components["schemas"]["SyncTombstone"][];
        };
        /** CreateOp */
        CreateOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create";
            /** Uid */
            uid: string;
            /** Page Title */
            page_title: string;
            /** Parent Uid */
            parent_uid?: string | null;
            /** Order Idx */
            order_idx: number;
            /** Text */
            text: string;
            /** Heading */
            heading?: number | null;
        };
        /** CreatePageRequest */
        CreatePageRequest: {
            /** Title */
            title: string;
        };
        /** DeleteOp */
        DeleteOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
            /** Uid */
            uid: string;
        };
        /** GroupItem */
        GroupItem: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
        };
        /**
         * GroupsPayload
         * @description Shared by /api/unlinked and /api/query.
         */
        GroupsPayload: {
            /** Groups */
            groups: components["schemas"]["BlockGroup"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JournalDay */
        JournalDay: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /** Exists */
            exists: boolean;
            /** Blocks */
            blocks: components["schemas"]["BlockNode"][];
        };
        /** JournalPayload */
        JournalPayload: {
            /** Days */
            days: components["schemas"]["JournalDay"][];
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
        };
        /** MoveOp */
        MoveOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Uid */
            uid: string;
            /** Parent Uid */
            parent_uid: string | null;
            /** Order Idx */
            order_idx: number;
            /** Page Title */
            page_title?: string | null;
        };
        /** OpBatch */
        OpBatch: {
            /** Client Id */
            client_id: string;
            /** Batch Id */
            batch_id?: string | null;
            /** Ops */
            ops: (components["schemas"]["CreateOp"] | components["schemas"]["UpdateTextOp"] | components["schemas"]["MoveOp"] | components["schemas"]["DeleteOp"] | components["schemas"]["SetCollapsedOp"] | components["schemas"]["SetHeadingOp"])[];
        };
        /** PageMeta */
        PageMeta: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
        };
        /** PagePayload */
        PagePayload: {
            page: components["schemas"]["PageMeta"];
            /** Blocks */
            blocks: components["schemas"]["BlockNode"][];
            backlinks: components["schemas"]["Backlinks"];
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
        };
        /** ReorderSidebarEntriesRequest */
        ReorderSidebarEntriesRequest: {
            /** Order */
            order: number[];
        };
        /** SearchBlockHit */
        SearchBlockHit: {
            /** Uid */
            uid: string;
            /** Page Title */
            page_title: string;
            /** Snippet */
            snippet: string;
        };
        /** SearchPageHit */
        SearchPageHit: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** SearchPayload */
        SearchPayload: {
            /** Pages */
            pages: components["schemas"]["SearchPageHit"][];
            /** Blocks */
            blocks: components["schemas"]["SearchBlockHit"][];
        };
        /** SetCollapsedOp */
        SetCollapsedOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_collapsed";
            /** Uid */
            uid: string;
            /** Collapsed */
            collapsed: boolean;
        };
        /** SetHeadingOp */
        SetHeadingOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_heading";
            /** Uid */
            uid: string;
            /** Heading */
            heading?: number | null;
        };
        /** SidebarNavEntry */
        SidebarNavEntry: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** SidebarNavPayload */
        SidebarNavPayload: {
            /** Entries */
            entries: components["schemas"]["SidebarNavEntry"][];
        };
        /** SnapshotPayload */
        SnapshotPayload: {
            /** Seq */
            seq: number;
            /** Pages */
            pages: components["schemas"]["SyncPage"][];
            /** Blocks */
            blocks: components["schemas"]["SyncBlock"][];
            /** Sidebar */
            sidebar: components["schemas"]["SyncSidebarEntry"][];
        };
        /** SyncBlock */
        SyncBlock: {
            /** Uid */
            uid: string;
            /** Page Id */
            page_id: number;
            /** Parent Uid */
            parent_uid: string | null;
            /** Order Idx */
            order_idx: number;
            /** Text */
            text: string;
            /** Heading */
            heading: number | null;
            /** Collapsed */
            collapsed: number;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
            /** Refs */
            refs: components["schemas"]["SyncRef"][];
        };
        /** SyncPage */
        SyncPage: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
        };
        /** SyncRef */
        SyncRef: {
            /** Target Page Id */
            target_page_id: number;
            /** Kind */
            kind: string;
        };
        /** SyncSidebarEntry */
        SyncSidebarEntry: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Order Idx */
            order_idx: number;
        };
        /** SyncTombstone */
        SyncTombstone: {
            /** Kind */
            kind: string;
            /** Entity Id */
            entity_id: string;
        };
        /** TitlesPayload */
        TitlesPayload: {
            /** Titles */
            titles: string[];
        };
        /** UpdateTextOp */
        UpdateTextOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update_text";
            /** Uid */
            uid: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_page_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openapi_schema_api_openapi_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_ops_api_ops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_refs_api_block_refs_get: {
        parameters: {
            query: {
                uids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockRefsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_page__title__get: {
        parameters: {
            query?: {
                bl_offset?: number;
                bl_limit?: number;
            };
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_page_api_page__title__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_page_api_pages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unlinked_api_unlinked_get: {
        parameters: {
            query: {
                title: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_api_journal_get: {
        parameters: {
            query?: {
                before?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_query_api_query_get: {
        parameters: {
            query: {
                expr: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    titles_api_titles_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitlesPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sidebar_api_sidebar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidebarNavPayload"];
                };
            };
        };
    };
    reorder_sidebar_entries_api_sidebar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderSidebarEntriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_sidebar_entry_api_sidebar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSidebarEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sidebar_entry_api_sidebar__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_changes_api_sync_changes_get: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_snapshot_api_sync_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPayload"];
                };
            };
        };
    };
    get_asset_assets__sha256___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
