/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Page */
        get: operations["login_page_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Openapi Schema */
        get: operations["openapi_schema_api_openapi_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ops */
        post: operations["post_ops_api_ops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/block-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block Refs
         * @description On-demand ((uid)) resolution for refs pasted after the page payload
         *     loaded (pkm-y6af). `uids` is comma-separated; unknown uids are omitted
         *     (the client renders them unresolved, same as the payload path).
         */
        get: operations["get_block_refs_api_block_refs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/block/{uid}/backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block Backlinks
         * @description The ((uid)) badge's popover read (pkm-d31f): who references this
         *     block. Same group shape and ordering as page backlinks; the count badge
         *     itself rides the page/journal payloads (block_ref_counts).
         */
        get: operations["get_block_backlinks_api_block__uid__backlinks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/block/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Block
         * @description One block's subtree plus its page and ancestor texts (pkm-w05j:
         *     the CLI/MCP `get <uid>` read; pages remain the only other read unit).
         */
        get: operations["get_block_api_block__uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/page/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_page__title__get"];
        put?: never;
        post?: never;
        /**
         * Delete Page
         * @description Deletes the page, its blocks, and any sidebar entry for it. Inbound
         *     [[links]] from other pages' block text are left as-is -- only the refs
         *     rows pointing at this page disappear (via target_page_id CASCADE).
         */
        delete: operations["delete_page_api_page__title__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Page
         * @description Idempotent: creating an existing page returns its row, not an error.
         */
        post: operations["create_page_api_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/page/{title}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename Page
         * @description Rename a page, rewriting every [[link]]/#tag/attr:: in block text.
         *     When the new title is taken: 409 unless allow_merge is true, in which
         *     case the source page is concatenated onto the target (source's
         *     top-level blocks appended after the target's, referencing text
         *     rewritten to the target, source page row dropped) -- a confirm-gated
         *     merge, not a silent overwrite. Case-sensitive throughout, like
         *     pages.title itself.
         */
        post: operations["rename_page_api_page__title__rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/unlinked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unlinked */
        get: operations["get_unlinked_api_unlinked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/current-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Work */
        get: operations["get_current_work_api_current_work_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Journal
         * @description Newest-first batch of non-empty daily pages (pkm-03x6). The head
         *     batch (no `before`) starts with today — auto-created so there is a
         *     page to compose into, even when empty — followed by the most recent
         *     non-empty days; `before` pages strictly backwards from that date. A
         *     day with no blocks but an inbound [[link]] from elsewhere counts as
         *     non-empty too, so a reminder written on another page surfaces under
         *     the day it points at (pkm-vvta) once that day would otherwise show.
         *     Empty, unreferenced days are omitted, and a batch shorter than `days`
         *     tells the client the journal is exhausted.
         *
         *     Each day carries its own linked-references preview
         *     (JOURNAL_BACKLINK_PREVIEW pages of them), so a scroll of N days is N/batch
         *     requests rather than one page read per day (pkm-5fak).
         */
        get: operations["get_journal_api_journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Journal
         * @description Deletes completely-empty daily pages from the 7 days before today
         *     (today is spared: the journal auto-creates it for composing). Stateless:
         *     every call re-checks the whole window, so a page emptied later by block
         *     moves is caught on the next load. A page whose blank block is still
         *     ((referenced)) from another page is spared -- deleting it would leave
         *     the reference dangling.
         */
        post: operations["cleanup_journal_api_journal_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Query */
        get: operations["run_query_api_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Titles
         * @description Page-title completion for the editor's [[ / # popup.
         */
        get: operations["titles_api_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todos
         * @description Blocks whose text starts with a {{TODO}} marker, grouped by page
         *     (pkm-w05j). SQL narrows to TODO-containing candidates; the shared
         *     pkm.todo matcher (the grammar's block-start rule, both bracket
         *     variants, '> ' quote prefix) decides. Marker-based rather than
         *     refs-based: the editor emits the bracket-less {{TODO}}, which
         *     creates no ref row to query.
         */
        get: operations["todos_api_todos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sidebar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sidebar */
        get: operations["get_sidebar_api_sidebar_get"];
        /** Reorder Sidebar Entries */
        put: operations["reorder_sidebar_entries_api_sidebar_put"];
        /** Add Sidebar Entry */
        post: operations["add_sidebar_entry_api_sidebar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sidebar/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Sidebar Entry */
        delete: operations["delete_sidebar_entry_api_sidebar__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Changes */
        get: operations["sync_changes_api_sync_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Snapshot */
        get: operations["sync_snapshot_api_sync_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Assets
         * @description LIKE search over description + filename (pkm-zc0c). Empty q lists
         *     most-recent uploads. LIKE, not FTS: personal-scale table, and no
         *     offline-parity burden. pkm-jdu3 adds type/date/linked filters,
         *     offset pagination, and a total count. linked/orphan filtering needs
         *     refs for every candidate, so that path scans the filtered set
         *     (personal scale keeps it cheap); linked=all computes refs only for
         *     the returned page.
         */
        get: operations["search_assets_api_assets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Asset
         * @description Delete an asset: strip every reference token from block text
         *     (blocks left empty with no children are deleted outright — asset
         *     deletion must never cascade away real content, so emptied parents
         *     are kept), drop the assets row, commit, then best-effort unlink the
         *     file. Commit-before-unlink: a crash leaves at worst an unreferenced
         *     file on disk, never a row pointing at a missing file. Asset URLs
         *     never contribute refs rows ([[link]]/#tag/attr:: only), so no refs
         *     reindex is needed; refs rows of deleted blocks go via FK cascade
         *     (the refs table has no FTS trigger — unlike blocks, where explicit
         *     per-uid DELETE is required to keep the FTS delete trigger firing).
         *     `block_refs` needs no reindex either, for the same reason:
         *     `strip_asset_tokens` removes only asset-embed tokens, a syntax disjoint
         *     from `((uid))`.
         */
        delete: operations["delete_asset_api_assets__sha256__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/export.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Assets
         * @description Zip the selected assets under their original filenames (name
         *     collisions get a short sha prefix via zip_arcnames). Form-encoded so
         *     the web app can drive it with a plain <form method="post"> and let
         *     the browser own the download. Unknown, malformed, duplicate, and
         *     missing-on-disk shas are skipped, not errors: the zip honestly
         *     contains what could be exported.
         *
         *     pkm-13ty: the selection's count and total bytes (summed from the
         *     `assets` table -- no file is opened just to measure it) are checked
         *     against MAX_EXPORT_ASSET_COUNT/MAX_EXPORT_TOTAL_BYTES before any zip
         *     is built; over either limit the request is refused with 413, never
         *     silently truncated. The archive itself is built in a temp directory
         *     and streamed back via FileResponse (not buffered whole in memory),
         *     with the directory removed once the response finishes, errors, or is
         *     interrupted (CleanupFileResponse).
         */
        post: operations["export_assets_api_assets_export_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{sha256}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_assets__sha256___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/describe-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe Status */
        get: operations["describe_status_api_assets_describe_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_assets_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/page/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Page Markdown */
        get: operations["export_page_markdown_api_export_page__title__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export All Markdown
         * @description Whole-graph export, zipped. pkm-13ty: built in a temp directory and
         *     streamed back via FileResponse rather than buffered whole in an
         *     in-memory BytesIO -- the graph has no size cap, so an unbounded
         *     number of pages/assets must not translate into an unbounded process
         *     allocation. The temp directory is removed once the response finishes,
         *     errors, or is interrupted (CleanupFileResponse); a failure before
         *     that point is cleaned up here directly and re-raised.
         */
        get: operations["export_all_markdown_api_export_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migrations/title-canonicalization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Title Canonicalization */
        get: operations["audit_title_canonicalization_api_migrations_title_canonicalization_get"];
        put?: never;
        /** Apply Title Canonicalization */
        post: operations["apply_title_canonicalization_api_migrations_title_canonicalization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Models the picker may offer; glm appears only when a z.ai key is
         *     configured, so the UI can hide rather than error on it. The default is
         *     glm when offered, sonnet otherwise.
         */
        get: operations["list_models_api_assistant_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_assistant_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_assistant_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Tool */
        post: operations["confirm_tool_api_assistant_conversations__conversation_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Conversation */
        post: operations["close_conversation_beacon"];
        /** Delete Conversation */
        delete: operations["delete_conversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddSidebarEntryRequest */
        AddSidebarEntryRequest: {
            /** Title */
            title: string;
        };
        /** AssetRef */
        AssetRef: {
            /** Uid */
            uid: string;
            /** Page Title */
            page_title: string;
        };
        /** AssetSearchItem */
        AssetSearchItem: {
            /** Sha256 */
            sha256: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /** Created At */
            created_at: number | null;
            /** Url */
            url: string;
            /** Description */
            description: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "described" | "failed" | "pending";
            /** Describe Error */
            describe_error: string | null;
            /** Refs */
            refs: components["schemas"]["AssetRef"][];
        };
        /** AssetSearchPayload */
        AssetSearchPayload: {
            /** Total */
            total: number;
            /** Assets */
            assets: components["schemas"]["AssetSearchItem"][];
        };
        /** AssetUploadResponse */
        AssetUploadResponse: {
            /** Sha256 */
            sha256: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /** Url */
            url: string;
            /** Existing */
            existing: boolean;
        };
        /** AssistantAck */
        AssistantAck: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** AssistantConversation */
        AssistantConversation: {
            /** Id */
            id: string;
            /** Model */
            model: string;
        };
        /** AssistantModels */
        AssistantModels: {
            /** Models */
            models: string[];
            /** Default */
            default: string;
        };
        /** BacklinkGroup */
        BacklinkGroup: {
            /** Page Id */
            page_id: number;
            /** Page Title */
            page_title: string;
            /** Items */
            items: components["schemas"]["BacklinkItem"][];
        };
        /** BacklinkItem */
        BacklinkItem: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
            /** Breadcrumbs */
            breadcrumbs: string[];
        };
        /** Backlinks */
        Backlinks: {
            /** Groups */
            groups: components["schemas"]["BacklinkGroup"][];
            /** Total Pages */
            total_pages: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * BlockBacklinksPayload
         * @description GET /api/block/{uid}/backlinks: every block referencing ((uid)),
         *     grouped like page backlinks. Unpaginated by design -- counts are small
         *     and nothing user-visible truncates silently (pkm-d31f).
         */
        BlockBacklinksPayload: {
            /** Groups */
            groups: components["schemas"]["BacklinkGroup"][];
        };
        /** BlockGroup */
        BlockGroup: {
            /** Page Id */
            page_id: number;
            /** Page Title */
            page_title: string;
            /** Items */
            items: components["schemas"]["GroupItem"][];
        };
        /** BlockNode */
        BlockNode: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
            /** Heading */
            heading: number | null;
            /** View Type */
            view_type: ("numbered" | "document") | null;
            /** Collapsed */
            collapsed: boolean;
            /** Order Idx */
            order_idx: number;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
            /** Children */
            children: components["schemas"]["BlockNode"][];
        };
        /**
         * BlockPayload
         * @description GET /api/block/{uid}: one block's subtree with page context.
         */
        BlockPayload: {
            page: components["schemas"]["PageMeta"];
            block: components["schemas"]["BlockNode"];
            /** Breadcrumbs */
            breadcrumbs: string[];
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
        };
        /** BlockRefText */
        BlockRefText: {
            /** Text */
            text: string;
            /** Page Title */
            page_title: string;
        };
        /**
         * BlockRefsPayload
         * @description GET /api/block-refs: on-demand ((uid)) resolution.
         */
        BlockRefsPayload: {
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
        };
        /** Body_export_assets_api_assets_export_zip_post */
        Body_export_assets_api_assets_export_zip_post: {
            /**
             * Sha256S
             * @default []
             */
            sha256s: string[];
        };
        /** Body_upload_asset_api_assets_post */
        Body_upload_asset_api_assets_post: {
            /** File */
            file: string;
        };
        /** ChangesPayload */
        ChangesPayload: {
            /**
             * Reset
             * @default false
             */
            reset: boolean;
            /** Generation */
            generation: string;
            /** Plain Space Title Canonicalization */
            plain_space_title_canonicalization: boolean;
            /** Next Since */
            next_since: number;
            /** Latest Seq */
            latest_seq: number;
            /** Pages */
            pages: components["schemas"]["SyncPage"][];
            /** Blocks */
            blocks: components["schemas"]["SyncBlock"][];
            /** Sidebar */
            sidebar: components["schemas"]["SyncSidebarEntry"][];
            /** Tombstones */
            tombstones: components["schemas"]["SyncTombstone"][];
        };
        /** ConfirmRequestBody */
        ConfirmRequestBody: {
            /** Tool Use Id */
            tool_use_id: string;
            /** Allow */
            allow: boolean;
        };
        /** CreateConversationRequest */
        CreateConversationRequest: {
            /** Model */
            model?: string | null;
        };
        /** CreateOp */
        CreateOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create";
            /** Uid */
            uid: string;
            /** Page Title */
            page_title: string;
            /** Parent Uid */
            parent_uid?: string | null;
            /** Order Idx */
            order_idx: number;
            /** Text */
            text: string;
            /** Heading */
            heading?: number | null;
            /** View Type */
            view_type?: ("numbered" | "document") | null;
        };
        /**
         * CreatePageOp
         * @description Durable push path for offline page creation (spec section 1): an
         *     empty page created offline has no block op to carry its title, so page
         *     creation is itself an op -- get_or_create semantics, safely replayable.
         */
        CreatePageOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create_page";
            /** Page Title */
            page_title: string;
        };
        /** CreatePageRequest */
        CreatePageRequest: {
            /** Title */
            title: string;
        };
        /** CurrentWorkPage */
        CurrentWorkPage: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: number;
        };
        /** CurrentWorkPayload */
        CurrentWorkPayload: {
            /** Sections */
            sections: components["schemas"]["CurrentWorkSection"][];
        };
        /** CurrentWorkSection */
        CurrentWorkSection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Pages */
            pages: components["schemas"]["CurrentWorkPage"][];
        };
        /** DeleteOp */
        DeleteOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
            /** Uid */
            uid: string;
        };
        /** DescribeStatusPayload */
        DescribeStatusPayload: {
            /** Enabled */
            enabled: boolean;
            /** Reason */
            reason: string | null;
        };
        /** GroupItem */
        GroupItem: {
            /** Uid */
            uid: string;
            /** Text */
            text: string;
        };
        /**
         * GroupsPayload
         * @description Shared by /api/unlinked and /api/todos.
         */
        GroupsPayload: {
            /** Groups */
            groups: components["schemas"]["BlockGroup"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JournalDay
         * @description One day of the journal scroll, complete: the day renders from this
         *     alone. `backlinks` is a preview page of the day's linked references
         *     (pkm-vvta) -- carried here because fetching them per day turned a scroll
         *     of N days into N page reads (pkm-5fak).
         */
        JournalDay: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /** Exists */
            exists: boolean;
            /** Blocks */
            blocks: components["schemas"]["BlockNode"][];
            backlinks: components["schemas"]["Backlinks"];
        };
        /** JournalPayload */
        JournalPayload: {
            /** Days */
            days: components["schemas"]["JournalDay"][];
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
            /** Block Ref Counts */
            block_ref_counts: {
                [key: string]: number;
            };
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
        };
        /** MoveOp */
        MoveOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Uid */
            uid: string;
            /** Parent Uid */
            parent_uid: string | null;
            /** Order Idx */
            order_idx: number;
            /** Page Title */
            page_title?: string | null;
        };
        /** OpBatch */
        OpBatch: {
            /** Client Id */
            client_id: string;
            /** Batch Id */
            batch_id: string;
            /** Ops */
            ops: (components["schemas"]["CreateOp"] | components["schemas"]["UpdateTextOp"] | components["schemas"]["MoveOp"] | components["schemas"]["DeleteOp"] | components["schemas"]["SetCollapsedOp"] | components["schemas"]["SetHeadingOp"] | components["schemas"]["SetViewTypeOp"] | components["schemas"]["CreatePageOp"])[];
        };
        /** PageMeta */
        PageMeta: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
        };
        /** PagePayload */
        PagePayload: {
            page: components["schemas"]["PageMeta"];
            /** Blocks */
            blocks: components["schemas"]["BlockNode"][];
            backlinks: components["schemas"]["Backlinks"];
            /** Block Ref Texts */
            block_ref_texts: {
                [key: string]: components["schemas"]["BlockRefText"];
            };
            /** Block Ref Counts */
            block_ref_counts: {
                [key: string]: number;
            };
        };
        /**
         * QueryPayload
         * @description GET /api/query: groups plus per-operand match counts so an empty
         *     result is steerable (bad query shape vs genuinely nothing).
         */
        QueryPayload: {
            /** Groups */
            groups: components["schemas"]["BlockGroup"][];
            /** Total */
            total: number;
            /** Ref Counts */
            ref_counts: {
                [key: string]: number;
            };
        };
        /** RenamePageRequest */
        RenamePageRequest: {
            /** New Title */
            new_title: string;
            /**
             * Allow Merge
             * @default false
             */
            allow_merge: boolean;
        };
        /**
         * RenamePageResponse
         * @description POST /api/page/{title}/rename: which branch ran, and the title the
         *     page now lives under (normalized, so it can differ from the requested
         *     one). `result` is a Literal so the web client can switch on it.
         */
        RenamePageResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "renamed" | "merged";
            /** Title */
            title: string;
        };
        /** ReorderSidebarEntriesRequest */
        ReorderSidebarEntriesRequest: {
            /** Order */
            order: number[];
        };
        /** ScanPayload */
        ScanPayload: {
            /** Queued */
            queued: number;
            /** Enabled */
            enabled: boolean;
            /** Reason */
            reason: string | null;
        };
        /** SearchBlockHit */
        SearchBlockHit: {
            /** Uid */
            uid: string;
            /** Page Title */
            page_title: string;
            /** Snippet */
            snippet: string;
        };
        /** SearchPageHit */
        SearchPageHit: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** SearchPayload */
        SearchPayload: {
            /** Pages */
            pages: components["schemas"]["SearchPageHit"][];
            /** Blocks */
            blocks: components["schemas"]["SearchBlockHit"][];
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Text */
            text: string;
        };
        /** SetCollapsedOp */
        SetCollapsedOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_collapsed";
            /** Uid */
            uid: string;
            /** Collapsed */
            collapsed: boolean;
        };
        /** SetHeadingOp */
        SetHeadingOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_heading";
            /** Uid */
            uid: string;
            /** Heading */
            heading?: number | null;
        };
        /** SetViewTypeOp */
        SetViewTypeOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_view_type";
            /** Uid */
            uid: string;
            /**
             * View Type
             * @enum {string}
             */
            view_type: "numbered" | "document";
        };
        /** SidebarNavEntry */
        SidebarNavEntry: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** SidebarNavPayload */
        SidebarNavPayload: {
            /** Entries */
            entries: components["schemas"]["SidebarNavEntry"][];
        };
        /** SnapshotPayload */
        SnapshotPayload: {
            /** Generation */
            generation: string;
            /** Plain Space Title Canonicalization */
            plain_space_title_canonicalization: boolean;
            /** Seq */
            seq: number;
            /** Pages */
            pages: components["schemas"]["SyncPage"][];
            /** Blocks */
            blocks: components["schemas"]["SyncBlock"][];
            /** Sidebar */
            sidebar: components["schemas"]["SyncSidebarEntry"][];
        };
        /** SyncBlock */
        SyncBlock: {
            /** Uid */
            uid: string;
            /** Page Id */
            page_id: number;
            /** Parent Uid */
            parent_uid: string | null;
            /** Order Idx */
            order_idx: number;
            /** Text */
            text: string;
            /** Heading */
            heading: number | null;
            /** View Type */
            view_type: ("numbered" | "document") | null;
            /** Collapsed */
            collapsed: number;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
            /** Refs */
            refs: components["schemas"]["SyncRef"][];
        };
        /** SyncPage */
        SyncPage: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: number | null;
            /** Updated At */
            updated_at: number | null;
        };
        /** SyncRef */
        SyncRef: {
            /** Target Page Id */
            target_page_id: number;
            /** Kind */
            kind: string;
        };
        /** SyncSidebarEntry */
        SyncSidebarEntry: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Order Idx */
            order_idx: number;
        };
        /** SyncTombstone */
        SyncTombstone: {
            /** Kind */
            kind: string;
            /** Entity Id */
            entity_id: string;
        };
        /** TitleMigrationApplyRequest */
        TitleMigrationApplyRequest: {
            /** Audit Digest */
            audit_digest: string;
        };
        /** TitleMigrationApplyResponse */
        TitleMigrationApplyResponse: {
            /** Digest */
            digest: string;
            /** Groups Applied */
            groups_applied: number;
            /** Pages Retitled */
            pages_retitled: number;
            /** Pages Merged */
            pages_merged: number;
            /** Blocks Moved */
            blocks_moved: number;
            /** Blocks Rewritten */
            blocks_rewritten: number;
            /** Generation */
            generation: string;
        };
        /** TitleMigrationAuditPayload */
        TitleMigrationAuditPayload: {
            /** Active */
            active: boolean;
            /** Digest */
            digest: string;
            /** Groups */
            groups: components["schemas"]["TitleMigrationGroup"][];
            /** Blockers */
            blockers: components["schemas"]["TitleMigrationBlocker"][];
        };
        /** TitleMigrationBlocker */
        TitleMigrationBlocker: {
            /** Page Id */
            page_id: number;
            /** Title */
            title: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "all_space" | "forbidden_syntax";
        };
        /** TitleMigrationGroup */
        TitleMigrationGroup: {
            /** Canonical Title */
            canonical_title: string;
            survivor: components["schemas"]["TitleMigrationPage"];
            /** Sources */
            sources: components["schemas"]["TitleMigrationPage"][];
            /** Has Clean Twin */
            has_clean_twin: boolean;
            /** Block Count */
            block_count: number;
            /** Inbound Ref Count */
            inbound_ref_count: number;
            /** Sidebar Count */
            sidebar_count: number;
        };
        /** TitleMigrationPage */
        TitleMigrationPage: {
            /** Page Id */
            page_id: number;
            /** Title */
            title: string;
        };
        /** TitlesPayload */
        TitlesPayload: {
            /** Titles */
            titles: string[];
        };
        /** UpdateTextOp */
        UpdateTextOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update_text";
            /** Uid */
            uid: string;
            /** Text */
            text: string;
            /** Base Text Hash */
            base_text_hash?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_page_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openapi_schema_api_openapi_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_ops_api_ops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_refs_api_block_refs_get: {
        parameters: {
            query: {
                uids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockRefsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_backlinks_api_block__uid__backlinks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockBacklinksPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_api_block__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_page__title__get: {
        parameters: {
            query?: {
                bl_offset?: number;
                bl_limit?: number;
            };
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_page_api_page__title__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_page_api_pages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_page_api_page__title__rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unlinked_api_unlinked_get: {
        parameters: {
            query: {
                title: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_work_api_current_work_get: {
        parameters: {
            query?: {
                now_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentWorkPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_api_journal_get: {
        parameters: {
            query?: {
                before?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_journal_api_journal_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                exact?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_query_api_query_get: {
        parameters: {
            query: {
                expr: string;
                expand?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    titles_api_titles_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitlesPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    todos_api_todos_get: {
        parameters: {
            query?: {
                page?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sidebar_api_sidebar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidebarNavPayload"];
                };
            };
        };
    };
    reorder_sidebar_entries_api_sidebar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderSidebarEntriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_sidebar_entry_api_sidebar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSidebarEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sidebar_entry_api_sidebar__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_changes_api_sync_changes_get: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_snapshot_api_sync_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPayload"];
                };
            };
        };
    };
    search_assets_api_assets_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                offset?: number;
                type?: "" | "image" | "pdf" | "document" | "other";
                from_ms?: number | null;
                to_ms?: number | null;
                linked?: "all" | "linked" | "orphan";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSearchPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_assets__sha256__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_assets_api_assets_export_zip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_export_assets_api_assets_export_zip_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_assets__sha256___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    describe_status_api_assets_describe_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescribeStatusPayload"];
                };
            };
        };
    };
    scan_api_assets_scan_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_page_markdown_api_export_page__title__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_all_markdown_api_export_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    audit_title_canonicalization_api_migrations_title_canonicalization_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleMigrationAuditPayload"];
                };
            };
        };
    };
    apply_title_canonicalization_api_migrations_title_canonicalization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitleMigrationApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleMigrationApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_assistant_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantModels"];
                };
            };
        };
    };
    create_conversation_api_assistant_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantConversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_assistant_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_tool_api_assistant_conversations__conversation_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_conversation_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
