// GENERATED by `uv run python -m pkm.schema_dump` (server/src/pkm/schema_dump.py).
// Do not edit; regenerate when schema.py BASE_DDL changes (server test enforces).
export const BASE_SCHEMA = `
CREATE TABLE IF NOT EXISTS pages(
  id          INTEGER PRIMARY KEY,
  title       TEXT NOT NULL UNIQUE,
  created_at  INTEGER,
  updated_at  INTEGER
);

-- ON DELETE CASCADE requires PRAGMA foreign_keys=ON per connection (SQLite default is OFF)
CREATE TABLE IF NOT EXISTS blocks(
  uid         TEXT PRIMARY KEY,
  page_id     INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  parent_uid  TEXT REFERENCES blocks(uid) ON DELETE CASCADE,
  order_idx   INTEGER NOT NULL,
  text        TEXT NOT NULL,
  heading     INTEGER,
  collapsed   INTEGER NOT NULL DEFAULT 0,
  created_at  INTEGER,
  updated_at  INTEGER,
  view_type   TEXT CHECK(view_type IN ('numbered','document'))
);
CREATE INDEX IF NOT EXISTS idx_blocks_page ON blocks(page_id);
CREATE INDEX IF NOT EXISTS idx_blocks_parent ON blocks(parent_uid);

CREATE TABLE IF NOT EXISTS refs(
  src_block_uid  TEXT NOT NULL REFERENCES blocks(uid) ON DELETE CASCADE,
  target_page_id INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  kind           TEXT NOT NULL CHECK(kind IN ('link','tag','attribute')),
  PRIMARY KEY (src_block_uid, target_page_id, kind)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS idx_refs_target ON refs(target_page_id);

-- pkm-d31f: incoming ((uid)) index, the block-level analogue of refs.
-- No FK on target_block_uid: an unresolved ((uid)) is a legal state (it
-- renders unresolved), so dangling rows are permitted and simply never
-- match a count query. Rows are derived from block text at every write
-- choke point (ops_apply.py, localOps.ts, apply.ts) and NEVER shipped
-- over sync -- targets are uids, needing no id resolution, and the
-- extractor is parity-pinned (refs_parity.json).
CREATE TABLE IF NOT EXISTS block_refs(
  src_block_uid    TEXT NOT NULL REFERENCES blocks(uid) ON DELETE CASCADE,
  target_block_uid TEXT NOT NULL,
  PRIMARY KEY (src_block_uid, target_block_uid)
) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS idx_block_refs_target ON block_refs(target_block_uid);

CREATE TABLE IF NOT EXISTS assets(
  sha256      TEXT PRIMARY KEY,
  filename    TEXT NOT NULL,
  mime        TEXT NOT NULL,
  size        INTEGER NOT NULL,
  created_at  INTEGER,
  -- pkm-zc0c: LLM-generated searchable description; all nullable.
  -- status is derived: described (description set) / failed
  -- (describe_error set) / pending (neither).
  description    TEXT,
  described_at   INTEGER,
  describe_error TEXT
);

-- keyed by blocks' implicit rowid: never VACUUM without rebuilding FTS ('rebuild' command)
CREATE VIRTUAL TABLE IF NOT EXISTS blocks_fts USING fts5(text, content='blocks');
CREATE TRIGGER IF NOT EXISTS blocks_fts_ai AFTER INSERT ON blocks BEGIN
  INSERT INTO blocks_fts(rowid, text) VALUES (new.rowid, new.text);
END;
CREATE TRIGGER IF NOT EXISTS blocks_fts_ad AFTER DELETE ON blocks BEGIN
  INSERT INTO blocks_fts(blocks_fts, rowid, text)
  VALUES ('delete', old.rowid, old.text);
END;
CREATE TRIGGER IF NOT EXISTS blocks_fts_au AFTER UPDATE OF text ON blocks BEGIN
  INSERT INTO blocks_fts(blocks_fts, rowid, text)
  VALUES ('delete', old.rowid, old.text);
  INSERT INTO blocks_fts(rowid, text) VALUES (new.rowid, new.text);
END;

CREATE VIRTUAL TABLE IF NOT EXISTS pages_fts USING fts5(title, content='pages', content_rowid='id');
CREATE TRIGGER IF NOT EXISTS pages_fts_ai AFTER INSERT ON pages BEGIN
  INSERT INTO pages_fts(rowid, title) VALUES (new.id, new.title);
END;
CREATE TRIGGER IF NOT EXISTS pages_fts_ad AFTER DELETE ON pages BEGIN
  INSERT INTO pages_fts(pages_fts, rowid, title)
  VALUES ('delete', old.id, old.title);
END;
CREATE TRIGGER IF NOT EXISTS pages_fts_au AFTER UPDATE OF title ON pages BEGIN
  INSERT INTO pages_fts(pages_fts, rowid, title)
  VALUES ('delete', old.id, old.title);
  INSERT INTO pages_fts(rowid, title) VALUES (new.id, new.title);
END;

CREATE TABLE IF NOT EXISTS sidebar_entries(
  id         INTEGER PRIMARY KEY,
  title      TEXT NOT NULL UNIQUE,
  order_idx  INTEGER NOT NULL
);
`;
