# pattern: Imperative Shell
"""Dump BASE_DDL as a TS artifact for the client replica (spec section 3):
uv run python -m pkm.schema_dump > ../web/src/replica/baseSchema.gen.ts
Only the base schema is exported -- exporting SERVER_DDL would install the
server's journal triggers in the replica. Guarded by
tests/test_schema_artifact.py (same pattern as openapi_dump)."""
from __future__ import annotations

from pkm.schema import BASE_DDL

HEADER = (
    "// GENERATED by `uv run python -m pkm.schema_dump` (server/src/pkm/"
    "schema_dump.py).\n// Do not edit; regenerate when schema.py BASE_DDL "
    "changes (server test enforces).\n")


def ts_module(ddl: str) -> str:
    escaped = (ddl.replace("\\", "\\\\").replace("`", "\\`")
               .replace("${", "\\${"))
    return f"{HEADER}export const BASE_SCHEMA = `{escaped}`;\n"


def main() -> int:
    print(ts_module(BASE_DDL), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
